// Curated list of popular global travel destinations ("City, Country").
// Used for instant, offline-friendly autocomplete suggestions (no API key, no
// billing). Live results from OpenStreetMap augment this list for the long tail.
export const POPULAR_DESTINATIONS = [
  // Asia
  "Tokyo, Japan",
  "Osaka, Japan",
  "Kyoto, Japan",
  "Hokkaido, Japan",
  "Bangkok, Thailand",
  "Phuket, Thailand",
  "Chiang Mai, Thailand",
  "Krabi, Thailand",
  "Singapore",
  "Bali, Indonesia",
  "Jakarta, Indonesia",
  "Kuala Lumpur, Malaysia",
  "Langkawi, Malaysia",
  "Hong Kong",
  "Macau",
  "Seoul, South Korea",
  "Busan, South Korea",
  "Beijing, China",
  "Shanghai, China",
  "Hanoi, Vietnam",
  "Ho Chi Minh City, Vietnam",
  "Da Nang, Vietnam",
  "Siem Reap, Cambodia",
  "Phnom Penh, Cambodia",
  "Vientiane, Laos",
  "Manila, Philippines",
  "Cebu, Philippines",
  "Boracay, Philippines",
  "Taipei, Taiwan",
  "New Delhi, India",
  "Mumbai, India",
  "Jaipur, India",
  "Goa, India",
  "Agra, India",
  "Bengaluru, India",
  "Udaipur, India",
  "Kathmandu, Nepal",
  "Pokhara, Nepal",
  "Colombo, Sri Lanka",
  "Malé, Maldives",
  "Thimphu, Bhutan",
  "Dubai, United Arab Emirates",
  "Abu Dhabi, United Arab Emirates",
  "Doha, Qatar",
  "Riyadh, Saudi Arabia",
  "Muscat, Oman",
  "Tashkent, Uzbekistan",
  "Samarkand, Uzbekistan",
  "Baku, Azerbaijan",
  "Tbilisi, Georgia",
  "Yerevan, Armenia",

  // Middle East
  "Istanbul, Turkey",
  "Cappadocia, Turkey",
  "Antalya, Turkey",
  "Tel Aviv, Israel",
  "Jerusalem, Israel",
  "Petra, Jordan",
  "Amman, Jordan",
  "Beirut, Lebanon",

  // Europe
  "Paris, France",
  "Nice, France",
  "Lyon, France",
  "Marseille, France",
  "London, United Kingdom",
  "Edinburgh, United Kingdom",
  "Manchester, United Kingdom",
  "Rome, Italy",
  "Venice, Italy",
  "Florence, Italy",
  "Milan, Italy",
  "Naples, Italy",
  "Amalfi Coast, Italy",
  "Barcelona, Spain",
  "Madrid, Spain",
  "Seville, Spain",
  "Valencia, Spain",
  "Granada, Spain",
  "Ibiza, Spain",
  "Lisbon, Portugal",
  "Porto, Portugal",
  "Madeira, Portugal",
  "Amsterdam, Netherlands",
  "Rotterdam, Netherlands",
  "Berlin, Germany",
  "Munich, Germany",
  "Frankfurt, Germany",
  "Hamburg, Germany",
  "Cologne, Germany",
  "Vienna, Austria",
  "Salzburg, Austria",
  "Hallstatt, Austria",
  "Innsbruck, Austria",
  "Prague, Czech Republic",
  "Budapest, Hungary",
  "Zurich, Switzerland",
  "Geneva, Switzerland",
  "Interlaken, Switzerland",
  "Lucerne, Switzerland",
  "Zermatt, Switzerland",
  "Brussels, Belgium",
  "Bruges, Belgium",
  "Copenhagen, Denmark",
  "Stockholm, Sweden",
  "Oslo, Norway",
  "Bergen, Norway",
  "Helsinki, Finland",
  "Reykjavik, Iceland",
  "Dublin, Ireland",
  "Athens, Greece",
  "Santorini, Greece",
  "Mykonos, Greece",
  "Crete, Greece",
  "Dubrovnik, Croatia",
  "Split, Croatia",
  "Zagreb, Croatia",
  "Warsaw, Poland",
  "Krakow, Poland",
  "Moscow, Russia",
  "Saint Petersburg, Russia",
  "Bucharest, Romania",
  "Sofia, Bulgaria",
  "Ljubljana, Slovenia",
  "Valletta, Malta",

  // Africa
  "Cairo, Egypt",
  "Luxor, Egypt",
  "Marrakech, Morocco",
  "Casablanca, Morocco",
  "Fes, Morocco",
  "Cape Town, South Africa",
  "Johannesburg, South Africa",
  "Nairobi, Kenya",
  "Zanzibar, Tanzania",
  "Arusha, Tanzania",
  "Addis Ababa, Ethiopia",
  "Accra, Ghana",
  "Tunis, Tunisia",
  "Victoria Falls, Zimbabwe",
  "Port Louis, Mauritius",
  "Victoria, Seychelles",

  // North America
  "New York, United States",
  "Los Angeles, United States",
  "San Francisco, United States",
  "Las Vegas, United States",
  "Miami, United States",
  "Chicago, United States",
  "Orlando, United States",
  "Washington, United States",
  "Boston, United States",
  "Seattle, United States",
  "New Orleans, United States",
  "Honolulu, United States",
  "San Diego, United States",
  "Toronto, Canada",
  "Vancouver, Canada",
  "Montreal, Canada",
  "Banff, Canada",
  "Mexico City, Mexico",
  "Cancun, Mexico",
  "Tulum, Mexico",
  "Playa del Carmen, Mexico",
  "Havana, Cuba",
  "Punta Cana, Dominican Republic",
  "San Juan, Puerto Rico",
  "Montego Bay, Jamaica",
  "Nassau, Bahamas",

  // South America
  "Rio de Janeiro, Brazil",
  "Sao Paulo, Brazil",
  "Buenos Aires, Argentina",
  "Lima, Peru",
  "Cusco, Peru",
  "Machu Picchu, Peru",
  "Santiago, Chile",
  "Bogota, Colombia",
  "Cartagena, Colombia",
  "Medellin, Colombia",
  "Quito, Ecuador",
  "La Paz, Bolivia",
  "Montevideo, Uruguay",

  // Oceania
  "Sydney, Australia",
  "Melbourne, Australia",
  "Brisbane, Australia",
  "Perth, Australia",
  "Gold Coast, Australia",
  "Cairns, Australia",
  "Auckland, New Zealand",
  "Queenstown, New Zealand",
  "Wellington, New Zealand",
  "Christchurch, New Zealand",
  "Nadi, Fiji",
  "Bora Bora, French Polynesia",
  "Papeete, French Polynesia",
];
